# Generated by Django 3.2 on 2022-09-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleMolde',
            new_name='SampleModel',
        ),
    ]
