# Generated by Django 3.2 on 2022-09-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220928_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '本のデータ'},
        ),
    ]
