# Generated by Django 3.2 on 2022-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20220928_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbmnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
