# Generated by Django 3.2 on 2022-09-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_thumbmnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumbmnail',
            new_name='thumbnail',
        ),
    ]
